import { commonConstants } from "../../constants"

Cypress.Commands.add('placeGTTBuyOrder', (symbol, triggerPrice, price, qty) => {
    cy.visit('/orders/gtt')
    cy.wait(2000)
    cy.xpath('//button[text()="New GTT"]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('(//input[@type="text"])[2]').type(symbol)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="NSE "]/preceding::div[@class="name"]/span[text()="' + symbol + '"]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//button[text()="Create GTT "]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//input[@label="Trigger price"]').clear().type(triggerPrice)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//input[@label="Price"]').clear().type(price)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//input[@label="Qty."]').clear().type(qty)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//div[text()="Place"]/..').click()
    cy.wait(800)
    cy.xpath('//td[contains(.,"BUY")]/../td/span/span[text()="' + symbol + '"]')
 })

 Cypress.Commands.add('placeGTTSellOrder', (symbol, stopLossTriggerPrice, stopLoss, sellTriggerPrice, sellPrice, qty) => {
    cy.visit('/orders/gtt')
    cy.wait(2000)
    cy.xpath('//button[text()="New GTT"]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('(//input[@type="text"])[2]').type(symbol)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="NSE "]/preceding::div[@class="name"]/span[text()="' + symbol + '"]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//button[text()="Create GTT "]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//label[text()="Sell"]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//label[text()="OCO"]').click()
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="Stoploss"]/following::input[@label="Trigger price"][1]').clear().type(stopLossTriggerPrice)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="Stoploss"]/following::input[@label="Price"][1]').clear().type(stopLoss)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="Stoploss"]/following::input[@label="Qty."][1]').clear().type(qty)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="Target"]/following::input[@label="Trigger price"][1]').clear().type(sellTriggerPrice)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="Target"]/following::input[@label="Price"][1]').clear().type(sellPrice)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//span[text()="Target"]/following::input[@label="Qty."][1]').clear().type(qty)
    cy.wait(Math.floor(Math.random() * 800) + 300)
    cy.xpath('//div[text()="Place"]/..').click()
    cy.wait(800)
    cy.xpath('//td[contains(.,"SELL")]/../td/span/span[text()="' + symbol + '"]')
 })

 Cypress.Commands.add('deleteGTTOrder', (symbol, buyOrSell) => {
    cy.visit('/orders/gtt')
    cy.wait(2000)
    if (buyOrSell == commonConstants.buy) {
        cy.wait(200)
        cy.xpath('//td[contains(.,"ACTIVE")]/../td[contains(.,"BUY")]/../td/span/span[text()="' + symbol + '"]').click()
        cy.wait(400)
        cy.xpath('//td[contains(.,"BUY")]/../td/span/span[text()="' + symbol + '"]/../../div').invoke('show').click()
        cy.wait(300)
        cy.xpath('//a[contains(.,"Delete")]').click()
        cy.wait(500)
        cy.xpath('//span[text()="Delete"]/..').click()
        cy.wait(500)
        cy.xpath('//button[text()="New GTT"]')
    }
    if (buyOrSell == commonConstants.sell) {
        cy.wait(200)
        cy.xpath('//td[contains(.,"ACTIVE")]/../td[contains(.,"SELL")]/../td/span/span[text()="' + symbol + '"]').click()
        cy.wait(1000)
        cy.xpath('//td[contains(.,"SELL")]/../td/span/span[text()="' + symbol + '"]/../../div').invoke('show').click()
        cy.wait(400)
        cy.xpath('//a[contains(.,"Delete")]').click()
        cy.wait(500)
        cy.xpath('//span[text()="Delete"]/..').click()
        cy.wait(500)
        cy.xpath('//button[text()="New GTT"]')
    }
 })